version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_content:/usr/share/nginx/html

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_THYRA_API_URL=${VITE_THYRA_API_URL}
    volumes:
      - static_content:/usr/share/nginx/html

volumes:
  static_content:

